Repository AI-x-optional/FE, pull requests merged in 2024-05, with the labels that each got.

#1 Add issue template & pr template
  .github/ISSUE_TEMPLATE/deploy.md
  .github/ISSUE_TEMPLATE/fix_bug.md
  .github/ISSUE_TEMPLATE/new_feature.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/ISSUE_TEMPLATE/request_feature.md
  .github/ISSUE_TEMPLATE/test.md
  .github/pull_request_template.md
Labels: ⚙️ Setting

#6 set router structure
  app/about/layout.js
  app/about/page.js
  app/components/header.js
  app/layout/main.js
  package-lock.json
  package.json
Labels: ✨ Feature

#2 Test pr template
  README.md
  app/about/layout.js
  app/about/page.js
  app/components/header.js
  app/layout/main.js
  issue.md
  package-lock.json
  package.json
Labels: ⚙️ Setting

#8 [FEATURE][STYLE] Header Component 추가 및 페이지 초안
  app/about/layout.js
  app/about/page.js
  app/bootcamp/layout.js
  app/bootcamp/page.js
  app/community/layout.js
  app/community/page.js
  app/components/header.js
  app/globals.css
  app/layout.js
  app/layout/main.js
  app/page.js
  app/qna/layout.js
  app/qna/page.js
  app/ui/header-links.js
  public/Logo.png
Labels: ✨ Feature

#12 [Style][institution] 기관 회원가입 페이지 UI 구현
  app/institution/login/page.js
  app/institution/signup/_components/FormInput.js
  app/institution/signup/_components/SearchBox.js
  app/institution/signup/_components/SearchInput.js
  app/institution/signup/page.js
Labels: 🎨 Style

#14 [Style][Components] 기관 회원가입 페이지 UI 구현
  app/about/layout.js
  app/about/page.js
  app/bootcamp/layout.js
  app/bootcamp/page.js
  app/community/layout.js
  app/community/page.js
  app/components/header.js
  app/globals.css
  app/institution/login/page.js
  app/layout.js
  app/layout/main.js
  app/page.js
  app/qna/layout.js
  app/qna/page.js
  app/ui/header-links.js
  public/Logo.png
Labels: 🎨 Style

#16 [Style][Components] 광고 배너 슬라이더 구현
  app/components/bannerSlider.js
  app/page.js
  package-lock.json
  package.json
  public/banner.jpeg
Labels: 🎨 Style

#17 [Style][generallogin] 일반 회원 로그인과 정보 입력 페이지 UI 구현
  app/generalLogin/page.js
  app/signupinfo/_components/signInfoButton.js
  app/signupinfo/_components/signupInfoModal.js
  app/signupinfo/page.js
  public/kakao_login_medium_wide.png
Labels: 🎨 Style

#18 [Style][] 로그인 선택 페이지 UI 구현
  app/components/header.js
  app/institution/signup/page.js
  app/login-select/page.js
Labels: 🎨 Style

#20 [Style][ BootCamp] 부트캠프 상세 조회 페이지 구현
  app/bootcamp/[bootCampId]/page.js
  public/image.jpeg
Labels: ✨ Feature, 🎨 Style

#25 [Style][BootCamp] 부트캠프 리스트 조회 및 필요 컴포넌트 제작
  app/bootcamp/[bootCampId]/page.js
  app/bootcamp/components/CourseTable.js
  app/bootcamp/components/filterSideBar.js
  app/bootcamp/page.js
  app/components/bannerSlider.js
  app/components/header.js
  app/generalLogin/page.js
  app/institution/login/page.js
  app/institution/signup/_components/FormInput.js
  app/institution/signup/_components/SearchBox.js
  app/institution/signup/_components/SearchInput.js
  app/institution/signup/page.js
  app/login-select/page.js
  app/page.js
  app/signupinfo/_components/signInfoButton.js
  app/signupinfo/_components/signupInfoModal.js
  app/signupinfo/page.js
  package-lock.json
  package.json
  public/banner.jpeg
  public/image.jpeg
  public/kakao_login_medium_wide.png
Labels: 🎨 Style
